# Generated by Django 3.2 on 2022-08-31 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
        ('issueapi', '0007_rename_project_title_issue_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapi.user'),
        ),
    ]
