# Generated by Django 3.2 on 2022-09-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issueapi', '0008_alter_issue_reporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
    ]
