# Generated by Django 3.2 on 2022-09-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueapi', '0009_auto_20220901_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('InProgress', 'In Progress'), ('InReiew', 'In Review'), ('CodeComplete', 'Code Complete'), ('Done', 'Done')], default='available', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Story', 'Story'), ('Task', 'Task'), ('Epic', 'Epic')], default='available', max_length=100),
        ),
    ]
