# Generated by Django 3.2 on 2022-09-01 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issueapi', '0010_auto_20220901_0637'),
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_field', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_value', models.CharField(max_length=400)),
                ('new_value', models.CharField(max_length=400)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issueapi.issue')),
                ('logged_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapi.user')),
            ],
        ),
    ]
