# Generated by Django 3.2 on 2022-09-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='previous_value',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
